sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t amirali1690/docker-react -f Dockerfile.dev . 


script: 
    - docker run -e CI=true amirali1690/docker-react npm run test